language: node_js

node_js:
  - "8"

os: [linux]
dist: trusty
sudo: required
cache:
  yarn: true

before_install:
  - curl -o- -L https://yarnpkg.com/install.sh | bash
  - export PATH=$HOME/.yarn/bin:$PATH

install:
  - yarn

script:
  - yarn test
